import type {Metadata} from "next";
import "./fonts.css";
import "./globals.css";
import Logo from "@/shared/ui/Logo";
import 'swiper/css';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body><Logo/>{children}</body>
        </html>
    );
}
